#!/bin/bash

set -eu
set -o pipefail

which ocrd >/dev/null 2>/dev/null || { echo "ocrd not in \$PATH. Panicking"; exit 1; }

SHAREDIR=$(cd $(dirname $0);pwd)

declare -A output_extensions=(
    ['image/tiff']='.tif'
    ['image/jp2']='.jp2'
    ['image/png']='.png'
)

main () {

    # Initialize the script
    source `ocrd bashlib filename`

    # Describe calling script to lib.bash
    ocrd__wrap "$SHAREDIR/ocrd-tool.json" "ocrd-im6convert" "$@"

    cd "${ocrd__argv[working_dir]}"
    page_id=${ocrd__argv[page_id]:-}
    in_file_grp=${ocrd__argv[input_file_grp]}
    out_file_grp=${ocrd__argv[output_file_grp]}
    mkdir -p $out_file_grp

    # Set output extension
    local output_extension="${output_extensions[${params['output-format']}]}"

    # Download the files and do the conversion
    local IFS=$'\n'
    files=($(ocrd workspace find \
        ${page_id:+-g} ${page_id:-} \
        -G $in_file_grp \
        -k local_filename \
        -k ID \
        -k pageId \
        --download))
    local IFS=$' \t\n'
    local n=0 zeros=0000
    for csv in "${files[@]}"; do
        let n+=1
        # Parse comma separated fields
        local IFS=$'\t'
        local fields=($csv)
        local IFS=$' \t\n'

        local in_file="${fields[0]}"
        local in_id="${fields[1]}"
        local pageid="${fields[2]:-}"

        if ! test -f "$in_file"; then
           echo "ERROR: input file \"$in_file\" ID=${in_id} (pageId=${pageid}) is not on disk" >&2
           continue
        fi

        # Output filename
        local out_id="${in_id//$in_file_grp/$out_file_grp}"
        if [ "x$out_id" = "x$in_id" ]; then
            out_id=${out_file_grp}_${zeros:0:$((4-${#n}))}$n
        fi
        local out_file="$out_file_grp/${out_id}$output_extension"

        # Actual conversion
        convert "$in_file" "$out_file"

        # Add the output files
        declare -a options
        if [ -n "$pageid" ]; then
            options=( -g $pageid )
        else
            options=()
        fi
        options+=( -G $out_file_grp
                   -m "${params['output-format']}"
                   -i "$out_id"
                   "$out_file" )
        ocrd workspace add "${options[@]}"
    done
}


main "$@"
